apiVersion: v2
name: documentation-site
description: A Helm chart for deploying the Docusaurus documentation site on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - documentation
  - docusaurus
  - static-site
home: https://github.com/vanvonlj/documentation-site
sources:
  - https://github.com/vanvonlj/documentation-site
maintainers:
  - name: vanvonlj
    email: vanvonlj@users.noreply.github.com
