apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: documentation-site
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: documentation-site
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxbot@users.noreply.github.com
        name: FluxBot
      messageTemplate: |
        chore: update documentation-site image

        Automation name: {{ .AutomationObject }}

        Files:
        {{ range $filename, $_ := .Updated.Files -}}
        - {{ $filename }}
        {{ end -}}

        Objects:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind }}/{{ $resource.Name }}
        {{ end -}}

        Images:
        {{ range $image, $_ := .Updated.Images -}}
        - {{$image.Repository}}:{{ $image.Tag }}
        {{ end -}}
    push:
      branch: flux-image-updates
  update:
    path: ./flux/prod
    strategy: Setters
