apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../base
  - values-configmap.yaml
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: documentation-site
