apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "documentation-site.fullname" . }}
  labels:
    {{- include "documentation-site.labels" . | nindent 4 }}
data:
  SITE_URL: {{ .Values.buildArgs.siteUrl | quote }}
  PROXY_BASE_URL: {{ .Values.buildArgs.proxyBaseUrl | quote }}
