apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../base
  - values-configmap.yaml
  - imagerepository.yaml
  - imagepolicy.yaml
  - imageupdateautomation.yaml
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: documentation-site
  - path: gitrepository-patch.yaml
    target:
      kind: GitRepository
      name: documentation-site
  - path: imagerepository-patch.yaml
    target:
      kind: ImageRepository
      name: documentation-site
